### ISSUE TITLE
Failed to determine git repository slug

### ISSUE THREAD

**Issue by josejimenezluna** [seantis/pytest-codecov#1]
Hi,

My CI workflow uploads reports to codecov after build, but I've been experiencing issues these last few days:

``` bash
$ pytest --cov=package --cov-config=.coveragerc --codecov --codecov-token=xxx tests/
```

However, I'm unable to upload coverage reports now:

```
====================================== Codecov.io upload =======================================

ERROR: Failed to determine git repository slug. Cannot upload without a valid slug.

```

It's a private repo but I'm providing the key. As mentioned this used to work flawlessly up until some days ago.

**Comment by Daverball** [comment]
The slug detection is very basic right now. It relies on GitPython being present and the CI workflow running inside a valid git repository with its remote url being in a fairly standard format. I'm not trying to do anything sophisticated right now. I am also not yet trying to check for environment variables from common CI services, like the bash uploader does.

You can manually supply the slug yourself using `--codecov-slug={org}/{project}`, but if its failing to determine the slug right now, it might also have trouble determining the commit hash and branch.

**Comment by josejimenezluna** [comment]
Dear @Daverball,

Thanks for your quick reply. Indeed it now has trouble determining the specific commit and branch. 

```
=============================================== Codecov.io upload ===============================================

WARNING: Failed to determine git repository branch.
WARNING: Failed to determine git commit.
Environment:
Slug:   xxx
Branch: None
Commit: None

Pinging codecov API...
ERROR: Invalid response from codecov API:
Invalid request parameters

```

Is there a way of specifying those manually? Would making the repository public help in this instance?

**Comment by Daverball** [comment]
The repository being public or private would not really have any impact. It does not interact with the GitHub API in any way.

You can absolutely manually supply a commit hash and branch. All can be supplied as environment variables or command line options:

`CODECOV_{SLUG|COMMIT|BRANCH}`

`--codecov-{slug|commit|branch}`

pytest should tell you about these options by the way, it dynamically adds configuration options from plugins to the help output, so `pytest --help` should contain a list of all the currently available --codecov options.

**Comment by josejimenezluna** [comment]
Dear @Daverball,

Many thanks for your help. The issue was finally resolved by uploading the coverage report as an xml file instead.

I will close this as it is evidently not related with your software.
